### ISSUE TITLE
Application crashes on download

### ISSUE THREAD

**Issue by lbarnabas** [Official-Husko/multporn-image-downloader-v2#1]
Crashes when attempting to download from multporn album https://multporn.net/comics/bawdy_falls. Tested using "D:\Downloads\bawdy-falls2" and "C:\Testing" in case it was a drive issue. Not sure if logs/dump are available anywhere to post here. Crash seems to happen regardless of Maximum Images field's content.

**Comment by Official-Husko** [comment]
Thank you for your Feedback, i have already received this problem once from an other user. I was not able to investigate it and because of that i will try to add a log system. Again thanks for your feedback, i will try to investigate the issue.

Regards
James

**Comment by lbarnabas** [comment]
Thanks for looking in to this. Let me know if you want assistance with debugging. I'm no coding expert, but my paying job is in QA, so I'd be happy to help out.

**Comment by oguh43** [comment]
@Ibarnabas At this time, the software only supports downloading one comic at a time. But i started working on this :)
