### ISSUE TITLE
i cant see the download button or resize the window (windows 8.1)

### ISSUE THREAD

**Issue by meeemo123** [Official-Husko/multporn-image-downloader-v2#2]
i can't see the download button and i can't resize the window so that i could click on the button..... and for that reason i cant download anything please fix 
![Capture](https://user-images.githubusercontent.com/64958283/81281574-b371dd00-9062-11ea-989d-b3a12166c74d.PNG)

**Comment by Official-Husko** [comment]
Thank you for reporting this error, due to an PC upgrade and a defective motherboard which i received in this state im currently not able to update nor fix any issues. Im sorry for the inconvenience and im sorry for the late reply. Once my pc is back i will have a look into it.

**Comment by oguh43** [comment]
@meemo123 you can try this version: https://github.com/oguh43/multporn-image-downloader-v2-alpha_branch/releases/

**Comment by oguh43** [comment]
Please try again with the newest version, as it contains logging. Thanks :)
